name: Publish Extension

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install tools
        run: npm install -g @vscode/vsce ovsx

      - name: Publish to VS Code Marketplace
        run: vsce publish -p ${{ secrets.VSCE_PAT }}

      - name: Publish to Open VSX
        run: ovsx publish -p ${{ secrets.OVSX_PAT }}
